name: Test & alpha release

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  release-node-alpha:
    uses: bgd-labs/icons/.github/workflows/release-node-alpha.yml@main
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}